on: workflow_dispatch
jobs:
  build-all:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: [ st_stm32mp157a_sodimm2_mx_defconfig ]
    steps:
      - uses: actions/checkout@v2
        with:
          path: buildroot-external
      - uses: actions/checkout@v2
        with:
          repository: cvetaevvitaliy/buildroot
          ref: 2021.11.1-stm32mp1
          path: buildroot
      - name: Check path
        run: echo "PATH=$(pwd)"
      - name: list
        run: ls -l
      - name: Configure Buildroot
        run: make -C buildroot BR2_EXTERNAL=$(pwd) O=../output ${{ matrix.config }}
      - name: Build Buildroot
        run: make -C buildroot BR2_EXTERNAL=$(pwd) O=../output uboot -j32
      - name: Run legal-info
        run: make -C buildroot BR2_EXTERNAL=$(pwd) O=../output legal-info
      - name: Compress sdcard.img
        run: gzip -9 output/images/sdcard.img
      - name: Store images
        uses: actions/upload-artifact@v2
        with:
          name: image-${{ matrix.config }}
          path: output/images/sdcard.img.gz
